// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `WebService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maoding.WebService.zeroc;

public interface WebService extends com.zeroc.Ice.Object
{
    AccountDTO getLogin(AccountDTO dto, com.zeroc.Ice.Current current);

    java.util.List<ProjectDTO> getProjects(java.util.Map<java.lang.String, java.lang.String> params, com.zeroc.Ice.Current current);

    ProjectDTO loadProjectDetails(String projectId, com.zeroc.Ice.Current current);

    ProjectDTO getIssueInfo(String projectId, com.zeroc.Ice.Current current);

    ProjectDTO getDesignTaskList(QueryProjectTaskDTO query, com.zeroc.Ice.Current current);

    TaskDTO getMyTaskList4(java.util.Map<java.lang.String, java.lang.String> params, com.zeroc.Ice.Current current);

    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::zeroc::WebService"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::zeroc::WebService";
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getLogin(WebService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        AccountDTO iceP_dto;
        iceP_dto = AccountDTO.ice_read(istr);
        inS.endReadParams();
        AccountDTO ret = obj.getLogin(iceP_dto, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        AccountDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getProjects(WebService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        java.util.Map<java.lang.String, java.lang.String> iceP_params;
        iceP_params = com.maoding.Common.zeroc.MapHelper.read(istr);
        inS.endReadParams();
        java.util.List<ProjectDTO> ret = obj.getProjects(iceP_params, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ProjectDTOListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_loadProjectDetails(WebService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_projectId;
        iceP_projectId = istr.readString();
        inS.endReadParams();
        ProjectDTO ret = obj.loadProjectDetails(iceP_projectId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ProjectDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getIssueInfo(WebService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_projectId;
        iceP_projectId = istr.readString();
        inS.endReadParams();
        ProjectDTO ret = obj.getIssueInfo(iceP_projectId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ProjectDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getDesignTaskList(WebService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        QueryProjectTaskDTO iceP_query;
        iceP_query = QueryProjectTaskDTO.ice_read(istr);
        inS.endReadParams();
        ProjectDTO ret = obj.getDesignTaskList(iceP_query, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ProjectDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getMyTaskList4(WebService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        java.util.Map<java.lang.String, java.lang.String> iceP_params;
        iceP_params = com.maoding.Common.zeroc.MapHelper.read(istr);
        inS.endReadParams();
        TaskDTO ret = obj.getMyTaskList4(iceP_params, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        TaskDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    final static String[] _iceOps =
    {
        "getDesignTaskList",
        "getIssueInfo",
        "getLogin",
        "getMyTaskList4",
        "getProjects",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "loadProjectDetails"
    };

    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_getDesignTaskList(this, in, current);
            }
            case 1:
            {
                return _iceD_getIssueInfo(this, in, current);
            }
            case 2:
            {
                return _iceD_getLogin(this, in, current);
            }
            case 3:
            {
                return _iceD_getMyTaskList4(this, in, current);
            }
            case 4:
            {
                return _iceD_getProjects(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 6:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 7:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 8:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 9:
            {
                return _iceD_loadProjectDetails(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
