// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `FileServer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maoding.FileServer.zeroc;

public class DownloadRequestDTO implements java.lang.Cloneable,
                                           java.io.Serializable
{
    public int requestId;

    public int getRequestId()
    {
        return requestId;
    }

    public void setRequestId(int requestId)
    {
        this.requestId = requestId;
    }

    public String scope;

    public String getScope()
    {
        return scope;
    }

    public void setScope(String scope)
    {
        this.scope = scope;
    }

    public String key;

    public String getKey()
    {
        return key;
    }

    public void setKey(String key)
    {
        this.key = key;
    }

    public int chunkId;

    public int getChunkId()
    {
        return chunkId;
    }

    public void setChunkId(int chunkId)
    {
        this.chunkId = chunkId;
    }

    public int chunkSize;

    public int getChunkSize()
    {
        return chunkSize;
    }

    public void setChunkSize(int chunkSize)
    {
        this.chunkSize = chunkSize;
    }

    public long pos;

    public long getPos()
    {
        return pos;
    }

    public void setPos(long pos)
    {
        this.pos = pos;
    }

    public int size;

    public int getSize()
    {
        return size;
    }

    public void setSize(int size)
    {
        this.size = size;
    }

    public java.util.Map<java.lang.String, java.lang.String> params;

    public java.util.Map<java.lang.String, java.lang.String> getParams()
    {
        return params;
    }

    public void setParams(java.util.Map<java.lang.String, java.lang.String> params)
    {
        this.params = params;
    }

    public DownloadRequestDTO()
    {
        this.scope = "";
        this.key = "";
    }

    public DownloadRequestDTO(int requestId, String scope, String key, int chunkId, int chunkSize, long pos, int size, java.util.Map<java.lang.String, java.lang.String> params)
    {
        this.requestId = requestId;
        this.scope = scope;
        this.key = key;
        this.chunkId = chunkId;
        this.chunkSize = chunkSize;
        this.pos = pos;
        this.size = size;
        this.params = params;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        DownloadRequestDTO r = null;
        if(rhs instanceof DownloadRequestDTO)
        {
            r = (DownloadRequestDTO)rhs;
        }

        if(r != null)
        {
            if(this.requestId != r.requestId)
            {
                return false;
            }
            if(this.scope != r.scope)
            {
                if(this.scope == null || r.scope == null || !this.scope.equals(r.scope))
                {
                    return false;
                }
            }
            if(this.key != r.key)
            {
                if(this.key == null || r.key == null || !this.key.equals(r.key))
                {
                    return false;
                }
            }
            if(this.chunkId != r.chunkId)
            {
                return false;
            }
            if(this.chunkSize != r.chunkSize)
            {
                return false;
            }
            if(this.pos != r.pos)
            {
                return false;
            }
            if(this.size != r.size)
            {
                return false;
            }
            if(this.params != r.params)
            {
                if(this.params == null || r.params == null || !this.params.equals(r.params))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::zeroc::DownloadRequestDTO");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, requestId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, scope);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, key);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, chunkId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, chunkSize);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, pos);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, size);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, params);
        return h_;
    }

    public DownloadRequestDTO clone()
    {
        DownloadRequestDTO c = null;
        try
        {
            c = (DownloadRequestDTO)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.requestId);
        ostr.writeString(this.scope);
        ostr.writeString(this.key);
        ostr.writeInt(this.chunkId);
        ostr.writeInt(this.chunkSize);
        ostr.writeLong(this.pos);
        ostr.writeInt(this.size);
        com.maoding.Common.zeroc.MapHelper.write(ostr, this.params);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.requestId = istr.readInt();
        this.scope = istr.readString();
        this.key = istr.readString();
        this.chunkId = istr.readInt();
        this.chunkSize = istr.readInt();
        this.pos = istr.readLong();
        this.size = istr.readInt();
        this.params = com.maoding.Common.zeroc.MapHelper.read(istr);
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, DownloadRequestDTO v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public DownloadRequestDTO ice_read(com.zeroc.Ice.InputStream istr)
    {
        DownloadRequestDTO v = new DownloadRequestDTO();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<DownloadRequestDTO> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, DownloadRequestDTO v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<DownloadRequestDTO> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(DownloadRequestDTO.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final DownloadRequestDTO _nullMarshalValue = new DownloadRequestDTO();

    public static final long serialVersionUID = 804526508L;
}
