// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `FileServer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maoding.FileServer.zeroc;

public class FileRequestDTO implements java.lang.Cloneable,
                                       java.io.Serializable
{
    public String id;

    public String getId()
    {
        return id;
    }

    public void setId(String id)
    {
        this.id = id;
    }

    public String nodeId;

    public String getNodeId()
    {
        return nodeId;
    }

    public void setNodeId(String nodeId)
    {
        this.nodeId = nodeId;
    }

    public String url;

    public String getUrl()
    {
        return url;
    }

    public void setUrl(String url)
    {
        this.url = url;
    }

    public String scope;

    public String getScope()
    {
        return scope;
    }

    public void setScope(String scope)
    {
        this.scope = scope;
    }

    public String key;

    public String getKey()
    {
        return key;
    }

    public void setKey(String key)
    {
        this.key = key;
    }

    public int mode;

    public int getMode()
    {
        return mode;
    }

    public void setMode(int mode)
    {
        this.mode = mode;
    }

    public java.util.Map<java.lang.String, java.lang.String> params;

    public java.util.Map<java.lang.String, java.lang.String> getParams()
    {
        return params;
    }

    public void setParams(java.util.Map<java.lang.String, java.lang.String> params)
    {
        this.params = params;
    }

    public FileRequestDTO()
    {
        this.id = "";
        this.nodeId = "";
        this.url = "";
        this.scope = "";
        this.key = "";
    }

    public FileRequestDTO(String id, String nodeId, String url, String scope, String key, int mode, java.util.Map<java.lang.String, java.lang.String> params)
    {
        this.id = id;
        this.nodeId = nodeId;
        this.url = url;
        this.scope = scope;
        this.key = key;
        this.mode = mode;
        this.params = params;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        FileRequestDTO r = null;
        if(rhs instanceof FileRequestDTO)
        {
            r = (FileRequestDTO)rhs;
        }

        if(r != null)
        {
            if(this.id != r.id)
            {
                if(this.id == null || r.id == null || !this.id.equals(r.id))
                {
                    return false;
                }
            }
            if(this.nodeId != r.nodeId)
            {
                if(this.nodeId == null || r.nodeId == null || !this.nodeId.equals(r.nodeId))
                {
                    return false;
                }
            }
            if(this.url != r.url)
            {
                if(this.url == null || r.url == null || !this.url.equals(r.url))
                {
                    return false;
                }
            }
            if(this.scope != r.scope)
            {
                if(this.scope == null || r.scope == null || !this.scope.equals(r.scope))
                {
                    return false;
                }
            }
            if(this.key != r.key)
            {
                if(this.key == null || r.key == null || !this.key.equals(r.key))
                {
                    return false;
                }
            }
            if(this.mode != r.mode)
            {
                return false;
            }
            if(this.params != r.params)
            {
                if(this.params == null || r.params == null || !this.params.equals(r.params))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::zeroc::FileRequestDTO");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, nodeId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, url);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, scope);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, key);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, mode);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, params);
        return h_;
    }

    public FileRequestDTO clone()
    {
        FileRequestDTO c = null;
        try
        {
            c = (FileRequestDTO)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.id);
        ostr.writeString(this.nodeId);
        ostr.writeString(this.url);
        ostr.writeString(this.scope);
        ostr.writeString(this.key);
        ostr.writeInt(this.mode);
        com.maoding.Common.zeroc.MapHelper.write(ostr, this.params);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.id = istr.readString();
        this.nodeId = istr.readString();
        this.url = istr.readString();
        this.scope = istr.readString();
        this.key = istr.readString();
        this.mode = istr.readInt();
        this.params = com.maoding.Common.zeroc.MapHelper.read(istr);
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, FileRequestDTO v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public FileRequestDTO ice_read(com.zeroc.Ice.InputStream istr)
    {
        FileRequestDTO v = new FileRequestDTO();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<FileRequestDTO> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, FileRequestDTO v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<FileRequestDTO> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(FileRequestDTO.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final FileRequestDTO _nullMarshalValue = new FileRequestDTO();

    public static final long serialVersionUID = 754344876L;
}
