// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `Notice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maoding.Notice.zeroc;

public interface NoticeServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default void createTopic(java.lang.String topic)
    {
        createTopic(topic, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void createTopic(java.lang.String topic, java.util.Map<String, String> context)
    {
        _iceI_createTopicAsync(topic, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> createTopicAsync(java.lang.String topic)
    {
        return _iceI_createTopicAsync(topic, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> createTopicAsync(java.lang.String topic, java.util.Map<String, String> context)
    {
        return _iceI_createTopicAsync(topic, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_createTopicAsync(java.lang.String iceP_topic, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "createTopic", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeSerializable(iceP_topic);
                 }, null);
        return f;
    }

    default java.util.List<java.lang.String> listTopic()
    {
        return listTopic(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default java.util.List<java.lang.String> listTopic(java.util.Map<String, String> context)
    {
        return _iceI_listTopicAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.util.List<java.lang.String>> listTopicAsync()
    {
        return _iceI_listTopicAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.util.List<java.lang.String>> listTopicAsync(java.util.Map<String, String> context)
    {
        return _iceI_listTopicAsync(context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<java.util.List<java.lang.String>> _iceI_listTopicAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.util.List<java.lang.String>> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "listTopic", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     java.util.List<java.lang.String> ret;
                     ret = com.maoding.Common.zeroc.StringListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default java.util.List<java.lang.String> listSubscribedTopic(String userId)
    {
        return listSubscribedTopic(userId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default java.util.List<java.lang.String> listSubscribedTopic(String userId, java.util.Map<String, String> context)
    {
        return _iceI_listSubscribedTopicAsync(userId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.util.List<java.lang.String>> listSubscribedTopicAsync(String userId)
    {
        return _iceI_listSubscribedTopicAsync(userId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.util.List<java.lang.String>> listSubscribedTopicAsync(String userId, java.util.Map<String, String> context)
    {
        return _iceI_listSubscribedTopicAsync(userId, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<java.util.List<java.lang.String>> _iceI_listSubscribedTopicAsync(String iceP_userId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.util.List<java.lang.String>> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "listSubscribedTopic", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                 }, istr -> {
                     java.util.List<java.lang.String> ret;
                     ret = com.maoding.Common.zeroc.StringListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default void notice(MessageDTO message, String topic)
    {
        notice(message, topic, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void notice(MessageDTO message, String topic, java.util.Map<String, String> context)
    {
        _iceI_noticeAsync(message, topic, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> noticeAsync(MessageDTO message, String topic)
    {
        return _iceI_noticeAsync(message, topic, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> noticeAsync(MessageDTO message, String topic, java.util.Map<String, String> context)
    {
        return _iceI_noticeAsync(message, topic, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_noticeAsync(MessageDTO iceP_message, String iceP_topic, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "notice", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     MessageDTO.ice_write(ostr, iceP_message);
                     ostr.writeString(iceP_topic);
                 }, null);
        return f;
    }

    default void noticeToUser(MessageDTO message, String id)
    {
        noticeToUser(message, id, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void noticeToUser(MessageDTO message, String id, java.util.Map<String, String> context)
    {
        _iceI_noticeToUserAsync(message, id, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> noticeToUserAsync(MessageDTO message, String id)
    {
        return _iceI_noticeToUserAsync(message, id, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> noticeToUserAsync(MessageDTO message, String id, java.util.Map<String, String> context)
    {
        return _iceI_noticeToUserAsync(message, id, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_noticeToUserAsync(MessageDTO iceP_message, String iceP_id, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "noticeToUser", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     MessageDTO.ice_write(ostr, iceP_message);
                     ostr.writeString(iceP_id);
                 }, null);
        return f;
    }

    default void noticeToTask(MessageDTO message, String id)
    {
        noticeToTask(message, id, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void noticeToTask(MessageDTO message, String id, java.util.Map<String, String> context)
    {
        _iceI_noticeToTaskAsync(message, id, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> noticeToTaskAsync(MessageDTO message, String id)
    {
        return _iceI_noticeToTaskAsync(message, id, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> noticeToTaskAsync(MessageDTO message, String id, java.util.Map<String, String> context)
    {
        return _iceI_noticeToTaskAsync(message, id, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_noticeToTaskAsync(MessageDTO iceP_message, String iceP_id, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "noticeToTask", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     MessageDTO.ice_write(ostr, iceP_message);
                     ostr.writeString(iceP_id);
                 }, null);
        return f;
    }

    default void noticeToProject(MessageDTO message, String id)
    {
        noticeToProject(message, id, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void noticeToProject(MessageDTO message, String id, java.util.Map<String, String> context)
    {
        _iceI_noticeToProjectAsync(message, id, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> noticeToProjectAsync(MessageDTO message, String id)
    {
        return _iceI_noticeToProjectAsync(message, id, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> noticeToProjectAsync(MessageDTO message, String id, java.util.Map<String, String> context)
    {
        return _iceI_noticeToProjectAsync(message, id, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_noticeToProjectAsync(MessageDTO iceP_message, String iceP_id, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "noticeToProject", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     MessageDTO.ice_write(ostr, iceP_message);
                     ostr.writeString(iceP_id);
                 }, null);
        return f;
    }

    default void noticeToCompany(MessageDTO message, String id)
    {
        noticeToCompany(message, id, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void noticeToCompany(MessageDTO message, String id, java.util.Map<String, String> context)
    {
        _iceI_noticeToCompanyAsync(message, id, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> noticeToCompanyAsync(MessageDTO message, String id)
    {
        return _iceI_noticeToCompanyAsync(message, id, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> noticeToCompanyAsync(MessageDTO message, String id, java.util.Map<String, String> context)
    {
        return _iceI_noticeToCompanyAsync(message, id, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_noticeToCompanyAsync(MessageDTO iceP_message, String iceP_id, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "noticeToCompany", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     MessageDTO.ice_write(ostr, iceP_message);
                     ostr.writeString(iceP_id);
                 }, null);
        return f;
    }

    default void subscribeTopic(String topic, NoticeClientPrx client)
    {
        subscribeTopic(topic, client, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void subscribeTopic(String topic, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        _iceI_subscribeTopicAsync(topic, client, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> subscribeTopicAsync(String topic, NoticeClientPrx client)
    {
        return _iceI_subscribeTopicAsync(topic, client, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> subscribeTopicAsync(String topic, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        return _iceI_subscribeTopicAsync(topic, client, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_subscribeTopicAsync(String iceP_topic, NoticeClientPrx iceP_client, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "subscribeTopic", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_topic);
                     ostr.writeProxy(iceP_client);
                 }, null);
        return f;
    }

    default void subscribeTopicToUser(String id, NoticeClientPrx client)
    {
        subscribeTopicToUser(id, client, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void subscribeTopicToUser(String id, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        _iceI_subscribeTopicToUserAsync(id, client, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> subscribeTopicToUserAsync(String id, NoticeClientPrx client)
    {
        return _iceI_subscribeTopicToUserAsync(id, client, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> subscribeTopicToUserAsync(String id, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        return _iceI_subscribeTopicToUserAsync(id, client, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_subscribeTopicToUserAsync(String iceP_id, NoticeClientPrx iceP_client, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "subscribeTopicToUser", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_id);
                     ostr.writeProxy(iceP_client);
                 }, null);
        return f;
    }

    default void subscribeTopicToTask(String id, NoticeClientPrx client)
    {
        subscribeTopicToTask(id, client, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void subscribeTopicToTask(String id, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        _iceI_subscribeTopicToTaskAsync(id, client, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> subscribeTopicToTaskAsync(String id, NoticeClientPrx client)
    {
        return _iceI_subscribeTopicToTaskAsync(id, client, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> subscribeTopicToTaskAsync(String id, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        return _iceI_subscribeTopicToTaskAsync(id, client, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_subscribeTopicToTaskAsync(String iceP_id, NoticeClientPrx iceP_client, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "subscribeTopicToTask", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_id);
                     ostr.writeProxy(iceP_client);
                 }, null);
        return f;
    }

    default void subscribeTopicToProject(java.lang.String id, NoticeClientPrx client)
    {
        subscribeTopicToProject(id, client, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void subscribeTopicToProject(java.lang.String id, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        _iceI_subscribeTopicToProjectAsync(id, client, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> subscribeTopicToProjectAsync(java.lang.String id, NoticeClientPrx client)
    {
        return _iceI_subscribeTopicToProjectAsync(id, client, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> subscribeTopicToProjectAsync(java.lang.String id, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        return _iceI_subscribeTopicToProjectAsync(id, client, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_subscribeTopicToProjectAsync(java.lang.String iceP_id, NoticeClientPrx iceP_client, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "subscribeTopicToProject", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeSerializable(iceP_id);
                     ostr.writeProxy(iceP_client);
                 }, null);
        return f;
    }

    default void subscribeTopicToCompany(String id, NoticeClientPrx client)
    {
        subscribeTopicToCompany(id, client, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void subscribeTopicToCompany(String id, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        _iceI_subscribeTopicToCompanyAsync(id, client, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> subscribeTopicToCompanyAsync(String id, NoticeClientPrx client)
    {
        return _iceI_subscribeTopicToCompanyAsync(id, client, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> subscribeTopicToCompanyAsync(String id, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        return _iceI_subscribeTopicToCompanyAsync(id, client, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_subscribeTopicToCompanyAsync(String iceP_id, NoticeClientPrx iceP_client, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "subscribeTopicToCompany", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_id);
                     ostr.writeProxy(iceP_client);
                 }, null);
        return f;
    }

    default void subscribeTopicToTaskList(java.util.List<java.lang.String> idList, NoticeClientPrx client)
    {
        subscribeTopicToTaskList(idList, client, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void subscribeTopicToTaskList(java.util.List<java.lang.String> idList, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        _iceI_subscribeTopicToTaskListAsync(idList, client, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> subscribeTopicToTaskListAsync(java.util.List<java.lang.String> idList, NoticeClientPrx client)
    {
        return _iceI_subscribeTopicToTaskListAsync(idList, client, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> subscribeTopicToTaskListAsync(java.util.List<java.lang.String> idList, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        return _iceI_subscribeTopicToTaskListAsync(idList, client, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_subscribeTopicToTaskListAsync(java.util.List<java.lang.String> iceP_idList, NoticeClientPrx iceP_client, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "subscribeTopicToTaskList", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     com.maoding.Common.zeroc.StringListHelper.write(ostr, iceP_idList);
                     ostr.writeProxy(iceP_client);
                 }, null);
        return f;
    }

    default void subscribeTopicToProjectList(java.util.List<java.lang.String> idList, NoticeClientPrx client)
    {
        subscribeTopicToProjectList(idList, client, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void subscribeTopicToProjectList(java.util.List<java.lang.String> idList, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        _iceI_subscribeTopicToProjectListAsync(idList, client, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> subscribeTopicToProjectListAsync(java.util.List<java.lang.String> idList, NoticeClientPrx client)
    {
        return _iceI_subscribeTopicToProjectListAsync(idList, client, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> subscribeTopicToProjectListAsync(java.util.List<java.lang.String> idList, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        return _iceI_subscribeTopicToProjectListAsync(idList, client, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_subscribeTopicToProjectListAsync(java.util.List<java.lang.String> iceP_idList, NoticeClientPrx iceP_client, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "subscribeTopicToProjectList", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     com.maoding.Common.zeroc.StringListHelper.write(ostr, iceP_idList);
                     ostr.writeProxy(iceP_client);
                 }, null);
        return f;
    }

    default void subscribeTopicToCompanyList(java.util.List<java.lang.String> idList, NoticeClientPrx client)
    {
        subscribeTopicToCompanyList(idList, client, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void subscribeTopicToCompanyList(java.util.List<java.lang.String> idList, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        _iceI_subscribeTopicToCompanyListAsync(idList, client, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> subscribeTopicToCompanyListAsync(java.util.List<java.lang.String> idList, NoticeClientPrx client)
    {
        return _iceI_subscribeTopicToCompanyListAsync(idList, client, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> subscribeTopicToCompanyListAsync(java.util.List<java.lang.String> idList, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        return _iceI_subscribeTopicToCompanyListAsync(idList, client, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_subscribeTopicToCompanyListAsync(java.util.List<java.lang.String> iceP_idList, NoticeClientPrx iceP_client, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "subscribeTopicToCompanyList", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     com.maoding.Common.zeroc.StringListHelper.write(ostr, iceP_idList);
                     ostr.writeProxy(iceP_client);
                 }, null);
        return f;
    }

    default void unSubscribeTopic(java.lang.String topic, NoticeClientPrx client)
    {
        unSubscribeTopic(topic, client, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void unSubscribeTopic(java.lang.String topic, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        _iceI_unSubscribeTopicAsync(topic, client, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> unSubscribeTopicAsync(java.lang.String topic, NoticeClientPrx client)
    {
        return _iceI_unSubscribeTopicAsync(topic, client, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> unSubscribeTopicAsync(java.lang.String topic, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        return _iceI_unSubscribeTopicAsync(topic, client, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_unSubscribeTopicAsync(java.lang.String iceP_topic, NoticeClientPrx iceP_client, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "unSubscribeTopic", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeSerializable(iceP_topic);
                     ostr.writeProxy(iceP_client);
                 }, null);
        return f;
    }

    default void unSubscribeTopicToUser(java.lang.String id, NoticeClientPrx client)
    {
        unSubscribeTopicToUser(id, client, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void unSubscribeTopicToUser(java.lang.String id, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        _iceI_unSubscribeTopicToUserAsync(id, client, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> unSubscribeTopicToUserAsync(java.lang.String id, NoticeClientPrx client)
    {
        return _iceI_unSubscribeTopicToUserAsync(id, client, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> unSubscribeTopicToUserAsync(java.lang.String id, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        return _iceI_unSubscribeTopicToUserAsync(id, client, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_unSubscribeTopicToUserAsync(java.lang.String iceP_id, NoticeClientPrx iceP_client, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "unSubscribeTopicToUser", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeSerializable(iceP_id);
                     ostr.writeProxy(iceP_client);
                 }, null);
        return f;
    }

    default void unSubscribeTopicToTask(java.lang.String id, NoticeClientPrx client)
    {
        unSubscribeTopicToTask(id, client, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void unSubscribeTopicToTask(java.lang.String id, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        _iceI_unSubscribeTopicToTaskAsync(id, client, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> unSubscribeTopicToTaskAsync(java.lang.String id, NoticeClientPrx client)
    {
        return _iceI_unSubscribeTopicToTaskAsync(id, client, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> unSubscribeTopicToTaskAsync(java.lang.String id, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        return _iceI_unSubscribeTopicToTaskAsync(id, client, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_unSubscribeTopicToTaskAsync(java.lang.String iceP_id, NoticeClientPrx iceP_client, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "unSubscribeTopicToTask", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeSerializable(iceP_id);
                     ostr.writeProxy(iceP_client);
                 }, null);
        return f;
    }

    default void unSubscribeTopicToProject(String id, NoticeClientPrx client)
    {
        unSubscribeTopicToProject(id, client, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void unSubscribeTopicToProject(String id, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        _iceI_unSubscribeTopicToProjectAsync(id, client, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> unSubscribeTopicToProjectAsync(String id, NoticeClientPrx client)
    {
        return _iceI_unSubscribeTopicToProjectAsync(id, client, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> unSubscribeTopicToProjectAsync(String id, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        return _iceI_unSubscribeTopicToProjectAsync(id, client, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_unSubscribeTopicToProjectAsync(String iceP_id, NoticeClientPrx iceP_client, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "unSubscribeTopicToProject", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_id);
                     ostr.writeProxy(iceP_client);
                 }, null);
        return f;
    }

    default void unSubscribeTopicToCompany(String id, NoticeClientPrx client)
    {
        unSubscribeTopicToCompany(id, client, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void unSubscribeTopicToCompany(String id, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        _iceI_unSubscribeTopicToCompanyAsync(id, client, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> unSubscribeTopicToCompanyAsync(String id, NoticeClientPrx client)
    {
        return _iceI_unSubscribeTopicToCompanyAsync(id, client, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> unSubscribeTopicToCompanyAsync(String id, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        return _iceI_unSubscribeTopicToCompanyAsync(id, client, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_unSubscribeTopicToCompanyAsync(String iceP_id, NoticeClientPrx iceP_client, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "unSubscribeTopicToCompany", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_id);
                     ostr.writeProxy(iceP_client);
                 }, null);
        return f;
    }

    default void unSubscribeTopicToTaskList(java.util.List<java.lang.String> idList, NoticeClientPrx client)
    {
        unSubscribeTopicToTaskList(idList, client, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void unSubscribeTopicToTaskList(java.util.List<java.lang.String> idList, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        _iceI_unSubscribeTopicToTaskListAsync(idList, client, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> unSubscribeTopicToTaskListAsync(java.util.List<java.lang.String> idList, NoticeClientPrx client)
    {
        return _iceI_unSubscribeTopicToTaskListAsync(idList, client, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> unSubscribeTopicToTaskListAsync(java.util.List<java.lang.String> idList, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        return _iceI_unSubscribeTopicToTaskListAsync(idList, client, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_unSubscribeTopicToTaskListAsync(java.util.List<java.lang.String> iceP_idList, NoticeClientPrx iceP_client, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "unSubscribeTopicToTaskList", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     com.maoding.Common.zeroc.StringListHelper.write(ostr, iceP_idList);
                     ostr.writeProxy(iceP_client);
                 }, null);
        return f;
    }

    default void unSubscribeTopicToProjectList(java.util.List<java.lang.String> idList, NoticeClientPrx client)
    {
        unSubscribeTopicToProjectList(idList, client, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void unSubscribeTopicToProjectList(java.util.List<java.lang.String> idList, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        _iceI_unSubscribeTopicToProjectListAsync(idList, client, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> unSubscribeTopicToProjectListAsync(java.util.List<java.lang.String> idList, NoticeClientPrx client)
    {
        return _iceI_unSubscribeTopicToProjectListAsync(idList, client, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> unSubscribeTopicToProjectListAsync(java.util.List<java.lang.String> idList, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        return _iceI_unSubscribeTopicToProjectListAsync(idList, client, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_unSubscribeTopicToProjectListAsync(java.util.List<java.lang.String> iceP_idList, NoticeClientPrx iceP_client, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "unSubscribeTopicToProjectList", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     com.maoding.Common.zeroc.StringListHelper.write(ostr, iceP_idList);
                     ostr.writeProxy(iceP_client);
                 }, null);
        return f;
    }

    default void unSubscribeTopicToCompanyList(java.util.List<java.lang.String> idList, NoticeClientPrx client)
    {
        unSubscribeTopicToCompanyList(idList, client, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void unSubscribeTopicToCompanyList(java.util.List<java.lang.String> idList, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        _iceI_unSubscribeTopicToCompanyListAsync(idList, client, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> unSubscribeTopicToCompanyListAsync(java.util.List<java.lang.String> idList, NoticeClientPrx client)
    {
        return _iceI_unSubscribeTopicToCompanyListAsync(idList, client, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> unSubscribeTopicToCompanyListAsync(java.util.List<java.lang.String> idList, NoticeClientPrx client, java.util.Map<String, String> context)
    {
        return _iceI_unSubscribeTopicToCompanyListAsync(idList, client, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_unSubscribeTopicToCompanyListAsync(java.util.List<java.lang.String> iceP_idList, NoticeClientPrx iceP_client, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "unSubscribeTopicToCompanyList", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     com.maoding.Common.zeroc.StringListHelper.write(ostr, iceP_idList);
                     ostr.writeProxy(iceP_client);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static NoticeServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), NoticeServicePrx.class, _NoticeServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static NoticeServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), NoticeServicePrx.class, _NoticeServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static NoticeServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), NoticeServicePrx.class, _NoticeServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static NoticeServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), NoticeServicePrx.class, _NoticeServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static NoticeServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, NoticeServicePrx.class, _NoticeServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static NoticeServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, NoticeServicePrx.class, _NoticeServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default NoticeServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (NoticeServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default NoticeServicePrx ice_adapterId(String newAdapterId)
    {
        return (NoticeServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default NoticeServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (NoticeServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default NoticeServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (NoticeServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default NoticeServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (NoticeServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default NoticeServicePrx ice_connectionCached(boolean newCache)
    {
        return (NoticeServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default NoticeServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (NoticeServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default NoticeServicePrx ice_secure(boolean b)
    {
        return (NoticeServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default NoticeServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (NoticeServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default NoticeServicePrx ice_preferSecure(boolean b)
    {
        return (NoticeServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default NoticeServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (NoticeServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default NoticeServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (NoticeServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default NoticeServicePrx ice_collocationOptimized(boolean b)
    {
        return (NoticeServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default NoticeServicePrx ice_twoway()
    {
        return (NoticeServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default NoticeServicePrx ice_oneway()
    {
        return (NoticeServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default NoticeServicePrx ice_batchOneway()
    {
        return (NoticeServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default NoticeServicePrx ice_datagram()
    {
        return (NoticeServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default NoticeServicePrx ice_batchDatagram()
    {
        return (NoticeServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default NoticeServicePrx ice_compress(boolean co)
    {
        return (NoticeServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default NoticeServicePrx ice_timeout(int t)
    {
        return (NoticeServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default NoticeServicePrx ice_connectionId(String connectionId)
    {
        return (NoticeServicePrx)_ice_connectionId(connectionId);
    }

    static String ice_staticId()
    {
        return "::zeroc::NoticeService";
    }
}
