// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `Common.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maoding.common.zeroc;

public interface CommonServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default com.maoding.fileServer.zeroc.FileServicePrx getFileService(String service, String config)
    {
        return getFileService(service, config, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default com.maoding.fileServer.zeroc.FileServicePrx getFileService(String service, String config, java.util.Map<String, String> context)
    {
        return _iceI_getFileServiceAsync(service, config, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<com.maoding.fileServer.zeroc.FileServicePrx> getFileServiceAsync(String service, String config)
    {
        return _iceI_getFileServiceAsync(service, config, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<com.maoding.fileServer.zeroc.FileServicePrx> getFileServiceAsync(String service, String config, java.util.Map<String, String> context)
    {
        return _iceI_getFileServiceAsync(service, config, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<com.maoding.fileServer.zeroc.FileServicePrx> _iceI_getFileServiceAsync(String iceP_service, String iceP_config, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<com.maoding.fileServer.zeroc.FileServicePrx> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getFileService", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_service);
                     ostr.writeString(iceP_config);
                 }, istr -> {
                     com.maoding.fileServer.zeroc.FileServicePrx ret;
                     ret = com.maoding.fileServer.zeroc.FileServicePrx.uncheckedCast(istr.readProxy());
                     return ret;
                 });
        return f;
    }

    default com.maoding.notice.zeroc.NoticeServicePrx getNoticeService(String service, String config)
    {
        return getNoticeService(service, config, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default com.maoding.notice.zeroc.NoticeServicePrx getNoticeService(String service, String config, java.util.Map<String, String> context)
    {
        return _iceI_getNoticeServiceAsync(service, config, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<com.maoding.notice.zeroc.NoticeServicePrx> getNoticeServiceAsync(String service, String config)
    {
        return _iceI_getNoticeServiceAsync(service, config, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<com.maoding.notice.zeroc.NoticeServicePrx> getNoticeServiceAsync(String service, String config, java.util.Map<String, String> context)
    {
        return _iceI_getNoticeServiceAsync(service, config, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<com.maoding.notice.zeroc.NoticeServicePrx> _iceI_getNoticeServiceAsync(String iceP_service, String iceP_config, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<com.maoding.notice.zeroc.NoticeServicePrx> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getNoticeService", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_service);
                     ostr.writeString(iceP_config);
                 }, istr -> {
                     com.maoding.notice.zeroc.NoticeServicePrx ret;
                     ret = com.maoding.notice.zeroc.NoticeServicePrx.uncheckedCast(istr.readProxy());
                     return ret;
                 });
        return f;
    }

    default com.maoding.storage.zeroc.StorageServicePrx getStorageService(String service, String config)
    {
        return getStorageService(service, config, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default com.maoding.storage.zeroc.StorageServicePrx getStorageService(String service, String config, java.util.Map<String, String> context)
    {
        return _iceI_getStorageServiceAsync(service, config, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<com.maoding.storage.zeroc.StorageServicePrx> getStorageServiceAsync(String service, String config)
    {
        return _iceI_getStorageServiceAsync(service, config, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<com.maoding.storage.zeroc.StorageServicePrx> getStorageServiceAsync(String service, String config, java.util.Map<String, String> context)
    {
        return _iceI_getStorageServiceAsync(service, config, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<com.maoding.storage.zeroc.StorageServicePrx> _iceI_getStorageServiceAsync(String iceP_service, String iceP_config, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<com.maoding.storage.zeroc.StorageServicePrx> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getStorageService", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_service);
                     ostr.writeString(iceP_config);
                 }, istr -> {
                     com.maoding.storage.zeroc.StorageServicePrx ret;
                     ret = com.maoding.storage.zeroc.StorageServicePrx.uncheckedCast(istr.readProxy());
                     return ret;
                 });
        return f;
    }

    default com.maoding.user.zeroc.UserServicePrx getUserService(String service, String config)
    {
        return getUserService(service, config, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default com.maoding.user.zeroc.UserServicePrx getUserService(String service, String config, java.util.Map<String, String> context)
    {
        return _iceI_getUserServiceAsync(service, config, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<com.maoding.user.zeroc.UserServicePrx> getUserServiceAsync(String service, String config)
    {
        return _iceI_getUserServiceAsync(service, config, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<com.maoding.user.zeroc.UserServicePrx> getUserServiceAsync(String service, String config, java.util.Map<String, String> context)
    {
        return _iceI_getUserServiceAsync(service, config, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<com.maoding.user.zeroc.UserServicePrx> _iceI_getUserServiceAsync(String iceP_service, String iceP_config, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<com.maoding.user.zeroc.UserServicePrx> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getUserService", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_service);
                     ostr.writeString(iceP_config);
                 }, istr -> {
                     com.maoding.user.zeroc.UserServicePrx ret;
                     ret = com.maoding.user.zeroc.UserServicePrx.uncheckedCast(istr.readProxy());
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CommonServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), CommonServicePrx.class, _CommonServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CommonServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), CommonServicePrx.class, _CommonServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CommonServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), CommonServicePrx.class, _CommonServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CommonServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), CommonServicePrx.class, _CommonServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static CommonServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, CommonServicePrx.class, _CommonServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static CommonServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, CommonServicePrx.class, _CommonServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default CommonServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (CommonServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default CommonServicePrx ice_adapterId(String newAdapterId)
    {
        return (CommonServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default CommonServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (CommonServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default CommonServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (CommonServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default CommonServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (CommonServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default CommonServicePrx ice_connectionCached(boolean newCache)
    {
        return (CommonServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default CommonServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (CommonServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default CommonServicePrx ice_secure(boolean b)
    {
        return (CommonServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default CommonServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (CommonServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default CommonServicePrx ice_preferSecure(boolean b)
    {
        return (CommonServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default CommonServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (CommonServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default CommonServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (CommonServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default CommonServicePrx ice_collocationOptimized(boolean b)
    {
        return (CommonServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default CommonServicePrx ice_twoway()
    {
        return (CommonServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default CommonServicePrx ice_oneway()
    {
        return (CommonServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default CommonServicePrx ice_batchOneway()
    {
        return (CommonServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default CommonServicePrx ice_datagram()
    {
        return (CommonServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default CommonServicePrx ice_batchDatagram()
    {
        return (CommonServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default CommonServicePrx ice_compress(boolean co)
    {
        return (CommonServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default CommonServicePrx ice_timeout(int t)
    {
        return (CommonServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default CommonServicePrx ice_connectionId(String connectionId)
    {
        return (CommonServicePrx)_ice_connectionId(connectionId);
    }

    static String ice_staticId()
    {
        return "::zeroc::CommonService";
    }
}
