// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `StorageData.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maoding.Storage.zeroc;

public class UpdateNodeFileDTO implements java.lang.Cloneable,
                                          java.io.Serializable
{
    public String serverTypeId;

    public String getServerTypeId()
    {
        return serverTypeId;
    }

    public void setServerTypeId(String serverTypeId)
    {
        this.serverTypeId = serverTypeId;
    }

    public String serverAddress;

    public String getServerAddress()
    {
        return serverAddress;
    }

    public void setServerAddress(String serverAddress)
    {
        this.serverAddress = serverAddress;
    }

    public String baseDir;

    public String getBaseDir()
    {
        return baseDir;
    }

    public void setBaseDir(String baseDir)
    {
        this.baseDir = baseDir;
    }

    public String fileTypeId;

    public String getFileTypeId()
    {
        return fileTypeId;
    }

    public void setFileTypeId(String fileTypeId)
    {
        this.fileTypeId = fileTypeId;
    }

    public String fileVersion;

    public String getFileVersion()
    {
        return fileVersion;
    }

    public void setFileVersion(String fileVersion)
    {
        this.fileVersion = fileVersion;
    }

    /**
     **/
    @Deprecated
    public String fileChecksum;

    /**
     **/
    @Deprecated
    public String getFileChecksum()
    {
        return fileChecksum;
    }

    /**
     **/
    @Deprecated
    public void setFileChecksum(String fileChecksum)
    {
        this.fileChecksum = fileChecksum;
    }

    public String majorTypeId;

    public String getMajorTypeId()
    {
        return majorTypeId;
    }

    public void setMajorTypeId(String majorTypeId)
    {
        this.majorTypeId = majorTypeId;
    }

    public String readOnlyKey;

    public String getReadOnlyKey()
    {
        return readOnlyKey;
    }

    public void setReadOnlyKey(String readOnlyKey)
    {
        this.readOnlyKey = readOnlyKey;
    }

    public long readOnlyFileLength;

    public long getReadOnlyFileLength()
    {
        return readOnlyFileLength;
    }

    public void setReadOnlyFileLength(long readOnlyFileLength)
    {
        this.readOnlyFileLength = readOnlyFileLength;
    }

    public String readOnlyFileMd5;

    public String getReadOnlyFileMd5()
    {
        return readOnlyFileMd5;
    }

    public void setReadOnlyFileMd5(String readOnlyFileMd5)
    {
        this.readOnlyFileMd5 = readOnlyFileMd5;
    }

    public String writableKey;

    public String getWritableKey()
    {
        return writableKey;
    }

    public void setWritableKey(String writableKey)
    {
        this.writableKey = writableKey;
    }

    public long writableFileLength;

    public long getWritableFileLength()
    {
        return writableFileLength;
    }

    public void setWritableFileLength(long writableFileLength)
    {
        this.writableFileLength = writableFileLength;
    }

    public String writableFileMd5;

    public String getWritableFileMd5()
    {
        return writableFileMd5;
    }

    public void setWritableFileMd5(String writableFileMd5)
    {
        this.writableFileMd5 = writableFileMd5;
    }

    public String mainFileId;

    public String getMainFileId()
    {
        return mainFileId;
    }

    public void setMainFileId(String mainFileId)
    {
        this.mainFileId = mainFileId;
    }

    public String mirrorTypeId;

    public String getMirrorTypeId()
    {
        return mirrorTypeId;
    }

    public void setMirrorTypeId(String mirrorTypeId)
    {
        this.mirrorTypeId = mirrorTypeId;
    }

    public String mirrorAddress;

    public String getMirrorAddress()
    {
        return mirrorAddress;
    }

    public void setMirrorAddress(String mirrorAddress)
    {
        this.mirrorAddress = mirrorAddress;
    }

    public String mirrorBaseDir;

    public String getMirrorBaseDir()
    {
        return mirrorBaseDir;
    }

    public void setMirrorBaseDir(String mirrorBaseDir)
    {
        this.mirrorBaseDir = mirrorBaseDir;
    }

    public String readOnlyMirrorKey;

    public String getReadOnlyMirrorKey()
    {
        return readOnlyMirrorKey;
    }

    public void setReadOnlyMirrorKey(String readOnlyMirrorKey)
    {
        this.readOnlyMirrorKey = readOnlyMirrorKey;
    }

    public String writableMirrorKey;

    public String getWritableMirrorKey()
    {
        return writableMirrorKey;
    }

    public void setWritableMirrorKey(String writableMirrorKey)
    {
        this.writableMirrorKey = writableMirrorKey;
    }

    public String lastModifyUserId;

    public String getLastModifyUserId()
    {
        return lastModifyUserId;
    }

    public void setLastModifyUserId(String lastModifyUserId)
    {
        this.lastModifyUserId = lastModifyUserId;
    }

    public String lastModifyRoleId;

    public String getLastModifyRoleId()
    {
        return lastModifyRoleId;
    }

    public void setLastModifyRoleId(String lastModifyRoleId)
    {
        this.lastModifyRoleId = lastModifyRoleId;
    }

    public UpdateNodeFileDTO()
    {
        this.serverTypeId = "";
        this.serverAddress = "";
        this.baseDir = "";
        this.fileTypeId = "";
        this.fileVersion = "";
        this.fileChecksum = "";
        this.majorTypeId = "";
        this.readOnlyKey = "";
        this.readOnlyFileMd5 = "";
        this.writableKey = "";
        this.writableFileMd5 = "";
        this.mainFileId = "";
        this.mirrorTypeId = "";
        this.mirrorAddress = "";
        this.mirrorBaseDir = "";
        this.readOnlyMirrorKey = "";
        this.writableMirrorKey = "";
        this.lastModifyUserId = "";
        this.lastModifyRoleId = "";
    }

    public UpdateNodeFileDTO(String serverTypeId, String serverAddress, String baseDir, String fileTypeId, String fileVersion, String fileChecksum, String majorTypeId, String readOnlyKey, long readOnlyFileLength, String readOnlyFileMd5, String writableKey, long writableFileLength, String writableFileMd5, String mainFileId, String mirrorTypeId, String mirrorAddress, String mirrorBaseDir, String readOnlyMirrorKey, String writableMirrorKey, String lastModifyUserId, String lastModifyRoleId)
    {
        this.serverTypeId = serverTypeId;
        this.serverAddress = serverAddress;
        this.baseDir = baseDir;
        this.fileTypeId = fileTypeId;
        this.fileVersion = fileVersion;
        this.fileChecksum = fileChecksum;
        this.majorTypeId = majorTypeId;
        this.readOnlyKey = readOnlyKey;
        this.readOnlyFileLength = readOnlyFileLength;
        this.readOnlyFileMd5 = readOnlyFileMd5;
        this.writableKey = writableKey;
        this.writableFileLength = writableFileLength;
        this.writableFileMd5 = writableFileMd5;
        this.mainFileId = mainFileId;
        this.mirrorTypeId = mirrorTypeId;
        this.mirrorAddress = mirrorAddress;
        this.mirrorBaseDir = mirrorBaseDir;
        this.readOnlyMirrorKey = readOnlyMirrorKey;
        this.writableMirrorKey = writableMirrorKey;
        this.lastModifyUserId = lastModifyUserId;
        this.lastModifyRoleId = lastModifyRoleId;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        UpdateNodeFileDTO r = null;
        if(rhs instanceof UpdateNodeFileDTO)
        {
            r = (UpdateNodeFileDTO)rhs;
        }

        if(r != null)
        {
            if(this.serverTypeId != r.serverTypeId)
            {
                if(this.serverTypeId == null || r.serverTypeId == null || !this.serverTypeId.equals(r.serverTypeId))
                {
                    return false;
                }
            }
            if(this.serverAddress != r.serverAddress)
            {
                if(this.serverAddress == null || r.serverAddress == null || !this.serverAddress.equals(r.serverAddress))
                {
                    return false;
                }
            }
            if(this.baseDir != r.baseDir)
            {
                if(this.baseDir == null || r.baseDir == null || !this.baseDir.equals(r.baseDir))
                {
                    return false;
                }
            }
            if(this.fileTypeId != r.fileTypeId)
            {
                if(this.fileTypeId == null || r.fileTypeId == null || !this.fileTypeId.equals(r.fileTypeId))
                {
                    return false;
                }
            }
            if(this.fileVersion != r.fileVersion)
            {
                if(this.fileVersion == null || r.fileVersion == null || !this.fileVersion.equals(r.fileVersion))
                {
                    return false;
                }
            }
            if(this.fileChecksum != r.fileChecksum)
            {
                if(this.fileChecksum == null || r.fileChecksum == null || !this.fileChecksum.equals(r.fileChecksum))
                {
                    return false;
                }
            }
            if(this.majorTypeId != r.majorTypeId)
            {
                if(this.majorTypeId == null || r.majorTypeId == null || !this.majorTypeId.equals(r.majorTypeId))
                {
                    return false;
                }
            }
            if(this.readOnlyKey != r.readOnlyKey)
            {
                if(this.readOnlyKey == null || r.readOnlyKey == null || !this.readOnlyKey.equals(r.readOnlyKey))
                {
                    return false;
                }
            }
            if(this.readOnlyFileLength != r.readOnlyFileLength)
            {
                return false;
            }
            if(this.readOnlyFileMd5 != r.readOnlyFileMd5)
            {
                if(this.readOnlyFileMd5 == null || r.readOnlyFileMd5 == null || !this.readOnlyFileMd5.equals(r.readOnlyFileMd5))
                {
                    return false;
                }
            }
            if(this.writableKey != r.writableKey)
            {
                if(this.writableKey == null || r.writableKey == null || !this.writableKey.equals(r.writableKey))
                {
                    return false;
                }
            }
            if(this.writableFileLength != r.writableFileLength)
            {
                return false;
            }
            if(this.writableFileMd5 != r.writableFileMd5)
            {
                if(this.writableFileMd5 == null || r.writableFileMd5 == null || !this.writableFileMd5.equals(r.writableFileMd5))
                {
                    return false;
                }
            }
            if(this.mainFileId != r.mainFileId)
            {
                if(this.mainFileId == null || r.mainFileId == null || !this.mainFileId.equals(r.mainFileId))
                {
                    return false;
                }
            }
            if(this.mirrorTypeId != r.mirrorTypeId)
            {
                if(this.mirrorTypeId == null || r.mirrorTypeId == null || !this.mirrorTypeId.equals(r.mirrorTypeId))
                {
                    return false;
                }
            }
            if(this.mirrorAddress != r.mirrorAddress)
            {
                if(this.mirrorAddress == null || r.mirrorAddress == null || !this.mirrorAddress.equals(r.mirrorAddress))
                {
                    return false;
                }
            }
            if(this.mirrorBaseDir != r.mirrorBaseDir)
            {
                if(this.mirrorBaseDir == null || r.mirrorBaseDir == null || !this.mirrorBaseDir.equals(r.mirrorBaseDir))
                {
                    return false;
                }
            }
            if(this.readOnlyMirrorKey != r.readOnlyMirrorKey)
            {
                if(this.readOnlyMirrorKey == null || r.readOnlyMirrorKey == null || !this.readOnlyMirrorKey.equals(r.readOnlyMirrorKey))
                {
                    return false;
                }
            }
            if(this.writableMirrorKey != r.writableMirrorKey)
            {
                if(this.writableMirrorKey == null || r.writableMirrorKey == null || !this.writableMirrorKey.equals(r.writableMirrorKey))
                {
                    return false;
                }
            }
            if(this.lastModifyUserId != r.lastModifyUserId)
            {
                if(this.lastModifyUserId == null || r.lastModifyUserId == null || !this.lastModifyUserId.equals(r.lastModifyUserId))
                {
                    return false;
                }
            }
            if(this.lastModifyRoleId != r.lastModifyRoleId)
            {
                if(this.lastModifyRoleId == null || r.lastModifyRoleId == null || !this.lastModifyRoleId.equals(r.lastModifyRoleId))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::zeroc::UpdateNodeFileDTO");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, serverTypeId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, serverAddress);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, baseDir);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, fileTypeId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, fileVersion);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, fileChecksum);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, majorTypeId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, readOnlyKey);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, readOnlyFileLength);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, readOnlyFileMd5);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, writableKey);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, writableFileLength);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, writableFileMd5);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, mainFileId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, mirrorTypeId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, mirrorAddress);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, mirrorBaseDir);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, readOnlyMirrorKey);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, writableMirrorKey);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lastModifyUserId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lastModifyRoleId);
        return h_;
    }

    public UpdateNodeFileDTO clone()
    {
        UpdateNodeFileDTO c = null;
        try
        {
            c = (UpdateNodeFileDTO)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.serverTypeId);
        ostr.writeString(this.serverAddress);
        ostr.writeString(this.baseDir);
        ostr.writeString(this.fileTypeId);
        ostr.writeString(this.fileVersion);
        ostr.writeString(this.fileChecksum);
        ostr.writeString(this.majorTypeId);
        ostr.writeString(this.readOnlyKey);
        ostr.writeLong(this.readOnlyFileLength);
        ostr.writeString(this.readOnlyFileMd5);
        ostr.writeString(this.writableKey);
        ostr.writeLong(this.writableFileLength);
        ostr.writeString(this.writableFileMd5);
        ostr.writeString(this.mainFileId);
        ostr.writeString(this.mirrorTypeId);
        ostr.writeString(this.mirrorAddress);
        ostr.writeString(this.mirrorBaseDir);
        ostr.writeString(this.readOnlyMirrorKey);
        ostr.writeString(this.writableMirrorKey);
        ostr.writeString(this.lastModifyUserId);
        ostr.writeString(this.lastModifyRoleId);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.serverTypeId = istr.readString();
        this.serverAddress = istr.readString();
        this.baseDir = istr.readString();
        this.fileTypeId = istr.readString();
        this.fileVersion = istr.readString();
        this.fileChecksum = istr.readString();
        this.majorTypeId = istr.readString();
        this.readOnlyKey = istr.readString();
        this.readOnlyFileLength = istr.readLong();
        this.readOnlyFileMd5 = istr.readString();
        this.writableKey = istr.readString();
        this.writableFileLength = istr.readLong();
        this.writableFileMd5 = istr.readString();
        this.mainFileId = istr.readString();
        this.mirrorTypeId = istr.readString();
        this.mirrorAddress = istr.readString();
        this.mirrorBaseDir = istr.readString();
        this.readOnlyMirrorKey = istr.readString();
        this.writableMirrorKey = istr.readString();
        this.lastModifyUserId = istr.readString();
        this.lastModifyRoleId = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, UpdateNodeFileDTO v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public UpdateNodeFileDTO ice_read(com.zeroc.Ice.InputStream istr)
    {
        UpdateNodeFileDTO v = new UpdateNodeFileDTO();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<UpdateNodeFileDTO> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, UpdateNodeFileDTO v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<UpdateNodeFileDTO> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(UpdateNodeFileDTO.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final UpdateNodeFileDTO _nullMarshalValue = new UpdateNodeFileDTO();

    public static final long serialVersionUID = -1625101133L;
}
